# Generated by Django 3.0.5 on 2023-07-06 01:50

import PhysicalExamResult.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExamResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exam', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.IntegerField()),
                ('result', djongo.models.fields.ArrayField(model_container=PhysicalExamResult.models.ExamResult)),
            ],
        ),
    ]
