# Generated by Django 4.0.1 on 2023-07-05 02:36

import RIPS.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalExamResults',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('date_exam', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.IntegerField()),
                ('result', djongo.models.fields.ArrayField(model_container=RIPS.models.ExamResult)),
            ],
        ),
    ]
